baseURL = '/'
languageCode = 'en-us'
title = 'René  Welches'
googleAnalytics = "G-KY2Z0BMY6Y"

[module]
[[module.imports]]
  path = 'github.com/zhaohuabing/hugo-theme-cleanwhite'

# Site Parameters
[params]
  header_image = "img/blog-start-banner.svg"
  description = "René's Blog and Notebook about homelab, AI, and technology"
  omit_categories = false
  SEOTitle = "Rene Welches' Blog"
  slogan = "TECH NOTES TO MYSELF"
  upstreamAttribution = true
  # SEO
  keyword  = ["Rene Welches' Blog", "blog", "homelab", "AI", "technology", "self-hosting"]
  
  # Social

  [params.social]
    rss = true
    github = "https://github.com/renewelches"
    linkedin = "https://www.linkedin.com/in/rené-welches-6512113/"
    #email = "rene.welches@gmail.com"

  [params.giscus]
    data_repo = "renewelches/renewelches-hugo-blog"
    data_repo_id = "R_kgDOQObS_w"
    data_category = "Announcements"
    data_category_id = "DIC_kwDOQObS_84C6i77"
    data_mapping = "pathname"
    data_reactions_enabled = "1"
    data_emit_metadata = "0"
    data_theme = "light"
    data_lang = "en"
    crossorigin = "anonymous"

  [[params.additional_menus]]
    title = "ABOUT"
    href = "about"

# Taxonomy
[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"