baseURL = 'https://blog.renewelches.com/'
languageCode = 'en-us'
title = 'René  Welches'

[module]
[[module.imports]]
  path = 'github.com/zhaohuabing/hugo-theme-cleanwhite'

# Site Parameters
[params]
  header_image = "img/bike.jpg"
  description = "René's Blog and Notebook about homelab, AI, and technology"
  omit_categories = false
  SEOTitle = "Rene Welches' Blog"
  slogan = "TECH NOTES TO MYSELF"
  upstreamAttribution = true

  # SEO
  keywords = ["Rene Welches' Blog", "blog", "homelab", "AI", "technology", "self-hosting"]

  # Social
  # twitter = "your_twitter"
  # github = "your_github"
  # linkedin = "your_linkedin"

  # Taxonomy
  [taxonomies]
    tag = "tags"
    category = "categories"
    archive = "archives"


  [[params.additional_menus]]
    title = "ABOUT"
    href = "/about/"